from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("dashboard/", views.member_dashboard, name="member_dashboard"),
    path("member/profile/", views.member_profile, name="member_profile"),
    path("member/notifications/", views.member_notifications, name="member_notifications"),
    path("apply/", views.application_create, name="application_create"),
    path("payments/<int:application_id>/upload/", views.payment_upload, name="payment_upload"),
    path("membership/status/", views.membership_status, name="membership_status"),
    path("membership/card/", views.card, name="membership_card"),
    path("membership/card/download/", views.card_pdf, name="membership_card_pdf"),
    path("membership/card/image/", views.card_image, name="membership_card_image"),
    path("membership/certificate/", views.membership_certificate, name="membership_certificate"),
    path("payments/receipt/", views.payment_receipt, name="payment_receipt"),
    path("verify/<uuid:public_id>/", views.verify_member, name="verify_member"),
    path("reports/", views.reports, name="reports"),
    path("reports/export/<str:report_type>/<str:file_type>/", views.export_report, name="export_report"),
    path("admin/dashboard/", views.staff_dashboard, name="staff_dashboard"),
    path("office/", views.staff_dashboard, name="staff_dashboard_legacy_root"),
    path("office/dashboard/", views.staff_dashboard, name="staff_dashboard_legacy"),
    path("admin/applications/", views.staff_applications, name="staff_applications"),
    path("admin/applications/<int:pk>/", views.staff_application_detail, name="staff_application_detail"),
    path("admin/applications/<int:pk>/action/", views.staff_application_action, name="staff_application_action"),
    path("admin/payments/", views.staff_payments, name="staff_payments"),
    path("admin/payments/<int:pk>/", views.staff_payment_detail, name="staff_payment_detail"),
    path("admin/payments/<int:pk>/action/", views.staff_payment_action, name="staff_payment_action"),
    path("admin/members/", views.staff_members, name="staff_members"),
    path("admin/members/<int:pk>/", views.staff_member_detail, name="staff_member_detail"),
    path("admin/membership-cards/", views.staff_membership_cards, name="staff_membership_cards"),
    path("admin/membership-cards/<int:pk>/download/", views.staff_member_card_pdf, name="staff_member_card_pdf"),
    path("admin/membership-cards/<int:pk>/image/", views.staff_member_card_image, name="staff_member_card_image"),
    path("admin/notifications/", views.staff_notifications, name="staff_notifications"),
    path("admin/reports/", views.staff_reports, name="staff_reports"),
    path("admin/masters/", views.staff_masters, name="staff_masters"),
    path("admin/settings/", views.staff_settings, name="staff_settings"),
    path("admin/profile/", views.staff_profile, name="staff_profile"),
    path(
        "admin-documents/<str:source>/<int:pk>/<str:field_name>/",
        views.admin_document_review,
        name="admin_document_review",
    ),
]
